name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./users

      - name: Run tests
        run: npm test
        working-directory: ./users

  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/api:${{ github.ref_name }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-config:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/vuitinhvl7x/VDT2024-api-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: config-repo

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yq

      - name: Update image tag in values.yaml
        run: |
          cd config-repo
          TAG_NAME=${GITHUB_REF#refs/tags/}
          yq eval '.image.tag = "${TAG_NAME}"' -i values.yaml
          git config --global user.email "xuanhai2708@gmail.com"
          git config --global user.name "vuitinhvl7x"
          git add values.yaml
          git commit -m "Update image tag to ${TAG_NAME}"
          git push
