name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./users

      - name: Run tests
        run: npm test
        working-directory: ./users

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Extract metadata (tags, labels) for Docker
        id: meta2
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/api

      - name: Print Docker tags
        run: echo ${{ steps.meta2.outputs.tags }}

      - name: Build and Push Docker API Image
        uses: docker/build-push-action@v4
        id: docker_build_backend
        with:
          context: ./users
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-config:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: https://github.com/vuitinhvl7x/VDT2024-api-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: config-repo

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yq

      - name: Update image tag in values.yaml
        run: |
          cd config-repo
          yq eval '.image.tag = "${{ github.ref_name }}"' -i values.yaml
          git config --global user.email "xuanhai2708@gmail.com"
          git config --global user.name "vuitinhvl7x"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}"
          git push
